apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: wachtpagina
  name: wachtpagina
spec:
  replicas: 2
  selector:
    app: wachtpagina
    deploymentconfig: wachtpagina
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 1
      maxUnavailable: 0
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: wachtpagina
        app: wachtpagina
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        name: wachtpagina
        ports:
        - containerPort: 8080
          protocol: TCP
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "31"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /favicon.ico
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /favicon.ico
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 45
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - wachtpagina
      from:
        kind: ImageStreamTag
        name: wachtpagina:latest
    type: ImageChange
