apiVersion: v1
kind: Service
metadata:
  labels:
    app: wachtpagina
  name: wachtpagina
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: wachtpagina
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
